# Generated by Django 4.2.3 on 2023-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=400, verbose_name=' человекопонятный URL')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='превью (изображение)')),
                ('date_of_create', models.DateTimeField(verbose_name='дата создания')),
                ('sign_of_publication', models.CharField(max_length=200, verbose_name='признак публикации')),
                ('quantity_of_views', models.FloatField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блоговая запись',
                'verbose_name_plural': 'блоговые записи',
                'ordering': ('header',),
            },
        ),
    ]
