# Generated by Django 4.2.3 on 2023-07-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quantity_of_views',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(blank=True, null=True, verbose_name='признак публикации'),
        ),
    ]
