# Generated by Django 4.2.3 on 2023-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_blog_quantity_of_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quantity_of_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=150, verbose_name=' человекопонятный URL'),
        ),
    ]
