# Generated by Django 4.2.3 on 2023-07-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_blog_quantity_of_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак публикации'),
        ),
    ]
