# Generated by Django 4.2.3 on 2023-07-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_blog_sign_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' человекопонятный URL'),
        ),
    ]
