# Generated by Django 4.2.3 on 2023-08-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_description_alter_product_name_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='sign_of_current_version',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак текущей версии'),
        ),
    ]
