# Generated by Django 4.2.3 on 2023-08-07 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_version_sign_of_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sign_of_current_version',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак текущей версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_versions', to='catalog.product', verbose_name='Продукт'),
        ),
    ]
