# Generated by Django 4.2.3 on 2023-08-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_sign_of_current_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sign_of_current_version',
        ),
    ]
